spring:
  application:
    name: spring-boot-tests
    jackson:
      property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employee
    baselineOnMigrate: true
    enabled: true
